package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assistenciatecnica generated by hbm2java
 */
@Entity
@Table(name = "assistenciatecnica", catalog = "lacodevidas02")
public class Assistenciatecnica implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private int id;
	private Usuario usuario;
	private Ocproduto ocproduto;
	private Date datainicio;
	private Date datafim;
	private String observacoes;
	private float valor;
	private Boolean deleted;

	public Assistenciatecnica() {
	}

	public Assistenciatecnica(int id, Usuario usuario, Ocproduto ocproduto,
			Date datainicio, Date datafim, float valor) {
		this.id = id;
		this.usuario = usuario;
		this.ocproduto = ocproduto;
		this.datainicio = datainicio;
		this.datafim = datafim;
		this.valor = valor;
	}

	public Assistenciatecnica(int id, Usuario usuario, Ocproduto ocproduto,
			Date datainicio, Date datafim, String observacoes, float valor) {
		this.id = id;
		this.usuario = usuario;
		this.ocproduto = ocproduto;
		this.datainicio = datainicio;
		this.datafim = datafim;
		this.observacoes = observacoes;
		this.valor = valor;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "montador", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne
	@JoinColumn(name = "ocproduto", nullable = false)
	public Ocproduto getOcproduto() {
		return this.ocproduto;
	}

	public void setOcproduto(Ocproduto ocproduto) {
		this.ocproduto = ocproduto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datainicio", nullable = false, length = 10)
	public Date getDatainicio() {
		return this.datainicio;
	}

	public void setDatainicio(Date datainicio) {
		this.datainicio = datainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datafim", nullable = false, length = 10)
	public Date getDatafim() {
		return this.datafim;
	}

	public void setDatafim(Date datafim) {
		this.datafim = datafim;
	}

	@Column(name = "observacoes", length = 65535)
	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

	@Column(name = "valor", nullable = false, precision = 5)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Column(name = "deleted", nullable= false)
	public Boolean getDeleted() {
		return deleted;
	}
	
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	
}
