package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "gcb")
public class Cliente implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String endereco;
	private String cidade;
	private String telefone;
	private String telefoneadicional;
	private int cpf;
	private int rg;
	private Date datadenascimento;
	private Boolean deleted;
	private Set ocs = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nome, String endereco, String cidade,
			String telefone, int cpf, int rg) {
		this.nome = nome;
		this.endereco = endereco;
		this.cidade = cidade;
		this.telefone = telefone;
		this.cpf = cpf;
		this.rg = rg;
	}

	public Cliente(String nome, String endereco, String cidade,
			String telefone, String telefoneadicional, int cpf, int rg,
			Date datadenascimento, Set ocs) {
		this.nome = nome;
		this.endereco = endereco;
		this.cidade = cidade;
		this.telefone = telefone;
		this.telefoneadicional = telefoneadicional;
		this.cpf = cpf;
		this.rg = rg;
		this.datadenascimento = datadenascimento;
		this.ocs = ocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 150)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", nullable = false, length = 150)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "cidade", nullable = false, length = 80)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "telefone", nullable = false, length = 12)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "telefoneadicional", length = 12)
	public String getTelefoneadicional() {
		return this.telefoneadicional;
	}

	public void setTelefoneadicional(String telefoneadicional) {
		this.telefoneadicional = telefoneadicional;
	}

	@Column(name = "cpf", nullable = false)
	public int getCpf() {
		return this.cpf;
	}

	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	@Column(name = "rg", nullable = false)
	public int getRg() {
		return this.rg;
	}

	public void setRg(int rg) {
		this.rg = rg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datadenascimento", length = 10)
	public Date getDatadenascimento() {
		return this.datadenascimento;
	}

	public void setDatadenascimento(Date datadenascimento) {
		this.datadenascimento = datadenascimento;
	}

	@OneToMany(targetEntity = Oc.class, mappedBy = "cliente")
	public Set getOcs() {
		return this.ocs;
	}

	public void setOcs(Set ocs) {
		this.ocs = ocs;
	}
	
	@Column(name = "deleted", nullable = false)
	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
	
	

}
