package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comissao generated by hbm2java
 */
@Entity
@Table(name = "comissao", catalog = "gcb")
public class Comissao implements java.io.Serializable {

	private Integer id;
	private Comissao comissao;
	private Usuario usuario;
	private int tipocomissao;
	private float percentual;
	private Set comissaos = new HashSet(0);

	public Comissao() {
	}

	public Comissao(Usuario usuario, int tipocomissao, float percentual) {
		this.usuario = usuario;
		this.tipocomissao = tipocomissao;
		this.percentual = percentual;
	}

	public Comissao(Comissao comissao, Usuario usuario, int tipocomissao,
			float percentual, Set comissaos) {
		this.comissao = comissao;
		this.usuario = usuario;
		this.tipocomissao = tipocomissao;
		this.percentual = percentual;
		this.comissaos = comissaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "usuariocomissaoconjunta")
	public Comissao getComissao() {
		return this.comissao;
	}

	public void setComissao(Comissao comissao) {
		this.comissao = comissao;
	}

	@ManyToOne
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "tipocomissao", nullable = false)
	public int getTipocomissao() {
		return this.tipocomissao;
	}

	public void setTipocomissao(int tipocomissao) {
		this.tipocomissao = tipocomissao;
	}

	@Column(name = "percentual", nullable = false, precision = 2)
	public float getPercentual() {
		return this.percentual;
	}

	public void setPercentual(float percentual) {
		this.percentual = percentual;
	}

	@OneToMany(targetEntity = Comissao.class, mappedBy = "comissao")
	public Set getComissaos() {
		return this.comissaos;
	}

	public void setComissaos(Set comissaos) {
		this.comissaos = comissaos;
	}

}
