package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contacontabil generated by hbm2java
 */
@Entity
@Table(name = "contacontabil", catalog = "blankerc_sgcb")
public class Contacontabil implements java.io.Serializable {

	private Integer id;
	private String tipo;
	private String nome;
	private List<Lancamento> lancamentos = new ArrayList<Lancamento>();
	

	public Contacontabil() {
	}

	public Contacontabil(String tipo, String nome) {
		this.tipo = tipo;
		this.nome = nome;
	}

	public Contacontabil(String tipo, String nome, List<Lancamento> lancamentos) {
		this.tipo = tipo;
		this.nome = nome;
		this.lancamentos = lancamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tipo", nullable = false, length = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "nome", nullable = false, length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(targetEntity = Lancamento.class, mappedBy = "contacontabil", fetch = FetchType.LAZY)
	public List<Lancamento> getLancamentos() {
		return this.lancamentos;
	}

	public void setLancamentos(List<Lancamento> lancamentos) {
		for(Lancamento lancamento : lancamentos){
			lancamento.setContacontabil(this);
		}
		this.lancamentos = lancamentos;
	}
	
	

}
