package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formapagamento generated by hbm2java
 */
@Entity
@Table(name = "formapagamento", catalog = "gcb")
public class Formapagamento implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Boolean deleted;
	private Boolean ehantecipacao;
	private List<CondicoesPagamento> condicoesPagamentos = new ArrayList<CondicoesPagamento>();

	public Formapagamento() {
	}

	public Formapagamento(String nome) {
		this.nome = nome;
	}

	public Formapagamento(String nome,List<CondicoesPagamento> condicoesPagamentos, Boolean deleted, Boolean ehantecipacao) {
		this.nome = nome;
		this.condicoesPagamentos = condicoesPagamentos;
		this.deleted = deleted;
		this.ehantecipacao = ehantecipacao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@Column(name = "deleted", nullable = false)
	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "ehantecipacao", nullable = false)
	public Boolean getEhantecipacao() {
		return ehantecipacao;
	}

	public void setEhantecipacao(Boolean ehantecipacao) {
		this.ehantecipacao = ehantecipacao;
	}

	@OneToMany(targetEntity = CondicoesPagamento.class, mappedBy = "formapagamento", cascade = CascadeType.ALL)
	public List<CondicoesPagamento> getCondicoesPagamentos() {
		return condicoesPagamentos;
	}

	public void setCondicoesPagamentos(List<CondicoesPagamento> condicoesPagamentos) {
		this.condicoesPagamentos = condicoesPagamentos;
	}

}
