package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Max;

import org.hibernate.validator.constraints.Length;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name = "fornecedor", catalog = "gcb")
public class Fornecedor implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Boolean ehrede;
	private String cnpj;
	private String telefone;
	private String endereco;
	private String cidade;
	private Boolean deleted;
	private Set produtos = new HashSet(0);
	private Set pedidos = new HashSet(0);

	public Fornecedor() {
	}

	public Fornecedor(String nome) {
		this.nome = nome;
	}

	public Fornecedor(Integer id, String nome, Boolean ehrede, String cnpj,
			String telefone, String endereco, String cidade, Boolean deleted,
			Set produtos, Set pedidos) {
		super();
		this.id = id;
		this.nome = nome;
		this.ehrede = ehrede;
		this.cnpj = cnpj;
		this.telefone = telefone;
		this.endereco = endereco;
		this.cidade = cidade;
		this.deleted = deleted;
		this.produtos = produtos;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "ehrede")
	public Boolean getEhrede() {
		return this.ehrede;
	}

	public void setEhrede(Boolean ehrede) {
		this.ehrede = ehrede;
	}

	@Column(name = "cnpj", length = 18)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}
	
	@Column(name="deleted")
	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name="telefone",length=14)
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name="endereco")
	@Length(max=150,message="Endereço em até 150 caracteres")
	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name="cidade")
	@Length(max=80,message="Endereço em até 80 caracteres")
	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@OneToMany(targetEntity = Produto.class, mappedBy = "fornecedor")
	public Set getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set produtos) {
		this.produtos = produtos;
	}

	@OneToMany(targetEntity = Pedido.class, mappedBy = "fornecedor")
	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	@Override
	public String toString() {
		return "Fornecedor [id=" + id + ", nome=" + nome + ", ehrede=" + ehrede
				+ ", cnpj=" + cnpj + ", deleted=" + deleted + "]";
	}
	
	

}
