package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Frete generated by hbm2java
 */
@Entity
@Table(name = "frete", catalog = "gcb")
public class Frete implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private Ocproduto ocproduto;
	private float valor;
	private Date datainicio;
	private Date datafim;
	private String observacoes;

	public Frete() {
	}

	public Frete(Usuario usuario, Ocproduto ocproduto, float valor,
			Date datainicio) {
		this.usuario = usuario;
		this.ocproduto = ocproduto;
		this.valor = valor;
		this.datainicio = datainicio;
	}

	public Frete(Usuario usuario, Ocproduto ocproduto, float valor,
			Date datainicio, Date datafim, String observacoes) {
		this.usuario = usuario;
		this.ocproduto = ocproduto;
		this.valor = valor;
		this.datainicio = datainicio;
		this.datafim = datafim;
		this.observacoes = observacoes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "freteiro", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne
	@JoinColumn(name = "ocproduto", nullable = false)
	public Ocproduto getOcproduto() {
		return this.ocproduto;
	}

	public void setOcproduto(Ocproduto ocproduto) {
		this.ocproduto = ocproduto;
	}

	@Column(name = "valor", nullable = false, precision = 5)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datainicio", nullable = false, length = 10)
	public Date getDatainicio() {
		return this.datainicio;
	}

	public void setDatainicio(Date datainicio) {
		this.datainicio = datainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datafim", length = 10)
	public Date getDatafim() {
		return this.datafim;
	}

	public void setDatafim(Date datafim) {
		this.datafim = datafim;
	}

	@Column(name = "observacoes", length = 65535)
	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

}
