package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lancamento generated by hbm2java
 */
@Entity
@Table(name = "lancamento", catalog = "blankerc_sgcb")
public class Lancamento implements java.io.Serializable {

	private int id;
	private Vale vale;
	private Contacontabil contacontabil;
	private String descricao;
	private float valor;
	private String lancamentocol;

	public Lancamento() {
	}

	public Lancamento(int id, Contacontabil contacontabil, String descricao,
			float valor) {
		this.id = id;
		this.contacontabil = contacontabil;
		this.descricao = descricao;
		this.valor = valor;
	}

	public Lancamento(int id, Vale vale, Contacontabil contacontabil,
			String descricao, float valor, String lancamentocol) {
		this.id = id;
		this.vale = vale;
		this.contacontabil = contacontabil;
		this.descricao = descricao;
		this.valor = valor;
		this.lancamentocol = lancamentocol;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vale")
	public Vale getVale() {
		return this.vale;
	}

	public void setVale(Vale vale) {
		this.vale = vale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contacontabil", nullable = false)
	public Contacontabil getContacontabil() {
		return this.contacontabil;
	}

	public void setContacontabil(Contacontabil contacontabil) {
		this.contacontabil = contacontabil;
	}

	@Column(name = "descricao", nullable = false, length = 80)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false, precision = 5)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	@Column(name = "lancamentocol", length = 45)
	public String getLancamentocol() {
		return this.lancamentocol;
	}

	public void setLancamentocol(String lancamentocol) {
		this.lancamentocol = lancamentocol;
	}

}
