package br.com.casabemestilo.model;


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ocproduto generated by hbm2java
 */
@Entity
@Table(name = "ocproduto", catalog = "gcb")
public class Ocproduto implements java.io.Serializable {

	private Integer id;
	private Status status;
	private Produto produto;
	private Oc oc;
	private String tiposaida;
	private Set montagems = new HashSet(0);
	private Set fretes = new HashSet(0);
	private Set assistenciatecnicas = new HashSet(0);
	private List<UsuarioFilial> usuarioFiliais = new ArrayList<UsuarioFilial>();

	public Ocproduto() {
	}

	public Ocproduto(Status status, Produto produto, Oc oc) {
		this.status = status;
		this.produto = produto;
		this.oc = oc;
	}

	public Ocproduto(Status status, Produto produto, Oc oc, String tiposaida,
			Set montagems, Set fretes, Set assistenciatecnicas) {
		this.status = status;
		this.produto = produto;
		this.oc = oc;
		this.tiposaida = tiposaida;
		this.montagems = montagems;
		this.fretes = fretes;
		this.assistenciatecnicas = assistenciatecnicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produto", nullable = false)
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne
	@JoinColumn(name = "oc", nullable = false)
	public Oc getOc() {
		return this.oc;
	}

	public void setOc(Oc oc) {
		this.oc = oc;
	}

	@Column(name = "tiposaida", length = 9)
	public String getTiposaida() {
		return this.tiposaida;
	}

	public void setTiposaida(String tiposaida) {
		this.tiposaida = tiposaida;
	}

	@OneToMany(targetEntity = Montagem.class, mappedBy = "ocproduto")
	public Set getMontagems() {
		return this.montagems;
	}

	public void setMontagems(Set montagems) {
		this.montagems = montagems;
	}

	@OneToMany(targetEntity = Frete.class, mappedBy = "ocproduto")
	public Set getFretes() {
		return this.fretes;
	}

	public void setFretes(Set fretes) {
		this.fretes = fretes;
	}

	@OneToMany(targetEntity = Assistenciatecnica.class,mappedBy = "ocproduto")
	public Set getAssistenciatecnicas() {
		return this.assistenciatecnicas;
	}

	public void setAssistenciatecnicas(Set assistenciatecnicas) {
		this.assistenciatecnicas = assistenciatecnicas;
	}
	
	@OneToMany(targetEntity= ComissaoUsuario.class, mappedBy = "ocProduto")
	public List<UsuarioFilial> getUsuarioFiliais() {
		return usuarioFiliais;
	}

	public void setUsuarioFiliais(List<UsuarioFilial> usuarioFiliais) {
		this.usuarioFiliais = usuarioFiliais;
	}
	
	

}
