package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento", catalog = "gcb")
public class Pagamento implements java.io.Serializable {

	private Integer id;
	private CondicoesPagamento condicoesPagamento;
	private Oc oc;
	private Date datalancamento;
	private Set parcelas = new HashSet(0);
	private Boolean deleted;
	private Float valor;

	public Pagamento() {
	}

	public Pagamento(CondicoesPagamento condicoesPagamento, Oc oc, Date datalancamento) {
		this.condicoesPagamento = condicoesPagamento;
		this.oc = oc;
		this.datalancamento = datalancamento;
	}

	public Pagamento(CondicoesPagamento condicoesPagamento, Oc oc, Date datalancamento,
			Set parcelas, Boolean deleted, Float valor) {
		this.condicoesPagamento = condicoesPagamento;
		this.oc = oc;
		this.datalancamento = datalancamento;
		this.parcelas = parcelas;
		this.deleted = deleted;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "condicoesPagamento", nullable = false)
	public CondicoesPagamento getCondicoesPagamento() {
		if(condicoesPagamento == null){
			condicoesPagamento = new CondicoesPagamento();
		}
		return this.condicoesPagamento;
	}

	public void setCondicoesPagamento(CondicoesPagamento condicoesPagamento) {
		this.condicoesPagamento = condicoesPagamento;
	}

	@ManyToOne
	@JoinColumn(name = "oc", nullable = false)
	public Oc getOc() {
		return this.oc;
	}

	public void setOc(Oc oc) {
		this.oc = oc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datalancamento", nullable = false, length = 10)
	public Date getDatalancamento() {
		return this.datalancamento;
	}

	public void setDatalancamento(Date datalancamento) {
		this.datalancamento = datalancamento;
	}

	@OneToMany(targetEntity = Parcela.class, mappedBy = "pagamento")
	public Set getParcelas() {
		return this.parcelas;
	}

	public void setParcelas(Set parcelas) {
		this.parcelas = parcelas;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "valor", nullable = false, scale = 6, precision = 2)
	public Float getValor() {
		return valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}
}
