package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento", catalog = "blankerc_sgcb")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Pagamento implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private CondicoesPagamento condicoesPagamento;
	private Oc oc;
	private Date datalancamento;
	private List<Parcela> parcelas = new ArrayList<Parcela>();
	private Boolean deleted;
	private Float valor;

	public Pagamento() {
	}

	public Pagamento(CondicoesPagamento condicoesPagamento, Oc oc, Date datalancamento) {
		this.condicoesPagamento = condicoesPagamento;
		this.oc = oc;
		this.datalancamento = datalancamento;
	}

	public Pagamento(CondicoesPagamento condicoesPagamento, Oc oc, Date datalancamento,
			List<Parcela> parcelas, Boolean deleted, Float valor) {
		this.condicoesPagamento = condicoesPagamento;
		this.oc = oc;
		this.datalancamento = datalancamento;
		this.parcelas = parcelas;
		this.deleted = deleted;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "condicoesPagamento", nullable = false)
	public CondicoesPagamento getCondicoesPagamento() {
		if(condicoesPagamento == null){
			condicoesPagamento = new CondicoesPagamento();
		}
		return this.condicoesPagamento;
	}

	public void setCondicoesPagamento(CondicoesPagamento condicoesPagamento) {
		this.condicoesPagamento = condicoesPagamento;
	}

	@ManyToOne
	@JoinColumn(name = "oc", nullable = false)
	public Oc getOc() {
		return this.oc;
	}

	public void setOc(Oc oc) {
		this.oc = oc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datalancamento", nullable = false, length = 10)
	public Date getDatalancamento() {
		if(this.datalancamento == null){
			this.datalancamento = new Date();
		}
		return this.datalancamento;
	}

	public void setDatalancamento(Date datalancamento) {
		this.datalancamento = datalancamento;
	}

	@OneToMany(targetEntity = Parcela.class, mappedBy = "pagamento", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public List<Parcela> getParcelas() {
		return this.parcelas;
	}

	public void setParcelas(List<Parcela> parcelas) {
		this.parcelas = parcelas;
		for(Parcela parcela : parcelas){
			parcela.setPagamento(this);
		}
		this.parcelas = parcelas;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		if(this.deleted == null){
			deleted = false;
		}
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "valor", nullable = false, scale = 6, precision = 2)
	public Float getValor() {
		if(this.valor == null){
			valor = new Float(0);
		}
		return valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	@Override
	public String toString() {
		return "Pagamento [id=" + id + ", datalancamento=" + datalancamento
				+ ", parcelas=" + parcelas + ", deleted=" + deleted
				+ ", valor=" + valor + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((condicoesPagamento == null) ? 0 : condicoesPagamento
						.hashCode());
		result = prime * result
				+ ((datalancamento == null) ? 0 : datalancamento.hashCode());
		result = prime * result + ((deleted == null) ? 0 : deleted.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((oc == null) ? 0 : oc.hashCode());
		result = prime * result
				+ ((parcelas == null) ? 0 : parcelas.hashCode());
		result = prime * result + ((valor == null) ? 0 : valor.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pagamento other = (Pagamento) obj;
		if (condicoesPagamento == null) {
			if (other.condicoesPagamento != null)
				return false;
		} else if (!condicoesPagamento.equals(other.condicoesPagamento))
			return false;
		if (datalancamento == null) {
			if (other.datalancamento != null)
				return false;
		} else if (!datalancamento.equals(other.datalancamento))
			return false;
		if (deleted == null) {
			if (other.deleted != null)
				return false;
		} else if (!deleted.equals(other.deleted))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (oc == null) {
			if (other.oc != null)
				return false;
		} else if (!oc.equals(other.oc))
			return false;
		if (parcelas == null) {
			if (other.parcelas != null)
				return false;
		} else if (!parcelas.equals(other.parcelas))
			return false;
		if (valor == null) {
			if (other.valor != null)
				return false;
		} else if (!valor.equals(other.valor))
			return false;
		return true;
	}
	
	
}
