package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "gcb")
public class Pedido implements java.io.Serializable {

	private Integer id;
	private Fornecedor fornecedor;
	private Date datasolicitacao;
	private Date datachegada;
	private String observacao;
	private Set pedidoprodutos = new HashSet(0);

	public Pedido() {
	}

	public Pedido(Fornecedor fornecedor, Date datasolicitacao) {
		this.fornecedor = fornecedor;
		this.datasolicitacao = datasolicitacao;
	}

	public Pedido(Fornecedor fornecedor, Date datasolicitacao,
			Date datachegada, String observacao, Set pedidoprodutos) {
		this.fornecedor = fornecedor;
		this.datasolicitacao = datasolicitacao;
		this.datachegada = datachegada;
		this.observacao = observacao;
		this.pedidoprodutos = pedidoprodutos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "fornecedor", nullable = false)
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datasolicitacao", nullable = false, length = 10)
	public Date getDatasolicitacao() {
		return this.datasolicitacao;
	}

	public void setDatasolicitacao(Date datasolicitacao) {
		this.datasolicitacao = datasolicitacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datachegada", length = 10)
	public Date getDatachegada() {
		return this.datachegada;
	}

	public void setDatachegada(Date datachegada) {
		this.datachegada = datachegada;
	}

	@Column(name = "observacao", length = 65535)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@OneToMany(targetEntity = Pedidoproduto.class, mappedBy = "pedido")
	public Set getPedidoprodutos() {
		return this.pedidoprodutos;
	}

	public void setPedidoprodutos(Set pedidoprodutos) {
		this.pedidoprodutos = pedidoprodutos;
	}

}
