package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Retencao generated by hbm2java
 */
@Entity
@Table(name = "retencao", catalog = "gcb")
public class Retencao implements java.io.Serializable {

	private Integer id;
	private Formapagamento formapagamento;
	private String nome;
	private float percentual;

	public Retencao() {
	}

	public Retencao(Formapagamento formapagamento, String nome, float percentual) {
		this.formapagamento = formapagamento;
		this.nome = nome;
		this.percentual = percentual;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formapagamento", nullable = false)
	public Formapagamento getFormapagamento() {
		return this.formapagamento;
	}

	public void setFormapagamento(Formapagamento formapagamento) {
		this.formapagamento = formapagamento;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "percentual", nullable = false, precision = 2)
	public float getPercentual() {
		return this.percentual;
	}

	public void setPercentual(float percentual) {
		this.percentual = percentual;
	}

}
