package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "lacodevidas02")
public class Status implements java.io.Serializable {

	private Integer id;
	private Boolean deleted;
	private String descricao;
	private Set ocs = new HashSet(0);
	private Set ocprodutos = new HashSet(0);

	public Status() {
	}

	public Status(String descricao) {
		this.descricao = descricao;
	}

	public Status(Boolean deleted, String descricao, Set ocs, Set ocprodutos) {
		this.deleted = deleted;
		this.descricao = descricao;
		this.ocs = ocs;
		this.ocprodutos = ocprodutos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(targetEntity = Oc.class, mappedBy = "status")
	public Set getOcs() {
		return this.ocs;
	}

	public void setOcs(Set ocs) {
		this.ocs = ocs;
	}

	@OneToMany(targetEntity = Ocproduto.class, mappedBy = "status")
	public Set getOcprodutos() {
		return this.ocprodutos;
	}

	public void setOcprodutos(Set ocprodutos) {
		this.ocprodutos = ocprodutos;
	}

}
