package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gcb")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private Perfil perfil;
	private Filial filial;
	private String nome;
	private Boolean deleted;
	private Set comissaos = new HashSet(0);
	private Set ocs = new HashSet(0);
	private Set fretes = new HashSet(0);
	private Set vales = new HashSet(0);
	private Set montagems = new HashSet(0);
	private Set assistenciatecnicas = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Perfil perfil, Filial filial, String nome) {
		this.perfil = perfil;
		this.filial = filial;
		this.nome = nome;
	}

	public Usuario(Perfil perfil, Filial filial, String nome, Boolean deleted,
			Set comissaos, Set ocs, Set fretes, Set vales, Set montagems,
			Set assistenciatecnicas) {
		this.perfil = perfil;
		this.filial = filial;
		this.nome = nome;
		this.deleted = deleted;
		this.comissaos = comissaos;
		this.ocs = ocs;
		this.fretes = fretes;
		this.vales = vales;
		this.montagems = montagems;
		this.assistenciatecnicas = assistenciatecnicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "perfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne
	@JoinColumn(name = "filial", nullable = false)
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@Column(name = "nome", nullable = false, length = 150)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@OneToMany(targetEntity = Comissao.class, mappedBy = "usuario")
	public Set getComissaos() {
		return this.comissaos;
	}

	public void setComissaos(Set comissaos) {
		this.comissaos = comissaos;
	}

	@OneToMany(targetEntity = Oc.class, mappedBy = "usuario")
	public Set getOcs() {
		return this.ocs;
	}

	public void setOcs(Set ocs) {
		this.ocs = ocs;
	}

	@OneToMany(targetEntity = Frete.class, mappedBy = "usuario")
	public Set getFretes() {
		return this.fretes;
	}

	public void setFretes(Set fretes) {
		this.fretes = fretes;
	}

	@OneToMany(targetEntity = Vale.class, mappedBy = "usuario")
	public Set getVales() {
		return this.vales;
	}

	public void setVales(Set vales) {
		this.vales = vales;
	}

	@OneToMany(targetEntity = Montagem.class, mappedBy = "usuario")
	public Set getMontagems() {
		return this.montagems;
	}

	public void setMontagems(Set montagems) {
		this.montagems = montagems;
	}

	@OneToMany(targetEntity = Assistenciatecnica.class, mappedBy = "usuario")
	public Set getAssistenciatecnicas() {
		return this.assistenciatecnicas;
	}

	public void setAssistenciatecnicas(Set assistenciatecnicas) {
		this.assistenciatecnicas = assistenciatecnicas;
	}

}
