package br.com.casabemestilo.model;

// Generated 24/05/2013 18:36:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vale generated by hbm2java
 */
@Entity
@Table(name = "vale", catalog = "lacodevidas02")
public class Vale implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private String descricao;
	private Boolean ehparafuncionario;
	private Set lancamentos = new HashSet(0);

	public Vale() {
	}

	public Vale(int id, String descricao) {
		this.id = id;
		this.descricao = descricao;
	}

	public Vale(int id, Usuario usuario, String descricao,
			Boolean ehparafuncionario, Set lancamentos) {
		this.id = id;
		this.usuario = usuario;
		this.descricao = descricao;
		this.ehparafuncionario = ehparafuncionario;
		this.lancamentos = lancamentos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "ehparafuncionario")
	public Boolean getEhparafuncionario() {
		return this.ehparafuncionario;
	}

	public void setEhparafuncionario(Boolean ehparafuncionario) {
		this.ehparafuncionario = ehparafuncionario;
	}

	@OneToMany(targetEntity = Lancamento.class, mappedBy = "vale")
	public Set getLancamentos() {
		return this.lancamentos;
	}

	public void setLancamentos(Set lancamentos) {
		this.lancamentos = lancamentos;
	}

}
